### ISSUE TITLE
Make compiling agnostic to paths

### ISSUE THREAD

**Issue by likern** [qtcreator-meson-plugin/qtcreator-meson-plugin#1]
Looks like you have some predefined paths.
I tried to follow described steps, but with modification:

`likern@likern:~/Projects/qtcreator-meson-plugin-build$ qmake -r ../qtcreator-meson-plugin/`
and got 
`Cannot read /home/trilader/code/qt-creator-opensource-src-4.5.1/src/qtcreatorplugin.pri: No such file or directory`

Looks like `trilader` - it is your user name.

**Comment by textshell** [comment]
That's why i wrote in the build instructions to override the path by using
```
qmake mesonprojectmanager.pro IDE_SOURCE_TREE="$IDE_SOURCE_TREE" IDE_BUILD_TREE="$IDE_BUILD_TREE"
```
But of course you can also change it in the .pro file if that suits your workflow better.

**Comment by likern** [comment]
My bad, I did something completely wrong. 
But is there a better way to distribute this plugin?

**Comment by likern** [comment]
For some people like me it's frustrating to handle with all of this stuff. I don't know anything about qmake and QT. and just want to make QtCreator working with meson - to build and debug GTK Glade UI editor.

**Comment by textshell** [comment]
I'm not sure how to improve distribution except offer a complete prebuild qtcreator+plugin bundle.
At least the qtcreator ABI doesn't seem to be stable between minor releases so if at all possible binaries would have to be per minor release. The long time hope is for decent meson support be part of stock qtcreator. This could be a base for that, or maybe something different, depending on how the GSoC (via upstream qtcreator) qtcreator meson support will pan out.

**Comment by likern** [comment]
Ok, I tried to compile against qt-creator-opensource-src-4.6.0 and it failed with this error:
`src/ninjamakestep.cpp:196:5: error: class ‘MesonProjectManager::NinjaMakeStepFactory’ does not have any field named ‘IBuildStepFactory’`

**Comment by likern** [comment]
Is this working only at specified version? Just wanted to use latest QtCreator, with all fresh features.

**Comment by textshell** [comment]
Yes. For now you need 4.5.x (tested with 4.5.1 and 4.5.2)
I think i should update the readme that the qtcreator version needs to match exactly. (qt creator changes api without strong backwards compatibility)
I don't expect porting to 4.6.0 will be very hard, but i've not yet started looking at that in detail.

**Comment by likern** [comment]
Ok, thank you. Will try exact version match.

**Comment by likern** [comment]
And I'll be waiting update for latest QtCreator version =)

**Comment by trilader** [comment]
I've added support for Qt Creator 4.6.0 and pushed it to master. Can you try to build it again?

**Comment by likern** [comment]
@trilader Sorry, I've deleted Qt Creator/Meson/Glade. Don't you that set of tools any-more.
