### ISSUE TITLE
not able to compile/build

### ISSUE THREAD

**Issue by iamsaiyan** [qtcreator-meson-plugin/qtcreator-meson-plugin#3]
unable to build the project . I am using Qt5.10.0 . 
my Qt source gives qt creator 4.7.0 as a build. 

i am getting following errors 
![1](https://user-images.githubusercontent.com/39567145/40587906-4b9f6b6a-61f3-11e8-8324-1b450cf66abe.png)

**Comment by trilader** [comment]
We've not yet looked into supporting Qt Creator 4.7.0.
QtCreator tends to change it's API almost every release. Version 4.6.0 should work and is tested. Also see the "Building from source" in README.md

**Comment by iamsaiyan** [comment]
can you give me your email ??
